# Generated by Django 3.2.2 on 2021-05-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
