# Generated by Django 3.2.2 on 2021-05-10 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('outlet_type', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('county', models.CharField(max_length=200)),
                ('constituency', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('gps_coordinates', models.CharField(max_length=200)),
                ('outlet_code', models.CharField(max_length=200)),
                ('outlet_person', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('amenities', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='deactivated', max_length=12)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('outlet_name',),
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('tran_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], default='in', max_length=12)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.AddField(
            model_name='outlet',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet', to='retailer.retailer'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='staff_recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet', to=settings.AUTH_USER_MODEL),
        ),
    ]
