# Generated by Django 3.2.2 on 2021-05-09 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20210509_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('type', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('constituency', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('gps_coordinates', models.CharField(max_length=200)),
                ('outlet_code', models.CharField(max_length=200)),
                ('outlet_person', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('amenities', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='deactivated', max_length=12)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('tran_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], default='in', max_length=12)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
