# Generated by Django 3.2.2 on 2021-05-11 04:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='retailer.outlettype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='outlet',
            name='outlet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet', to='retailer.outlettype'),
        ),
    ]
