# Generated by Django 3.2.2 on 2021-05-10 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='retailer',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
