# Generated by Django 3.2.2 on 2021-05-09 09:11

from django.db import migrations, models
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='outlet',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outlet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='deactivated', max_length=12),
        ),
        migrations.AddField(
            model_name='outlet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to=inventory.models.user_directory_path),
        ),
    ]
