# Generated by Django 3.2.3 on 2021-08-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
