# Generated by Django 3.2.3 on 2021-06-05 13:59

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_alter_outlet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='outlet',
            name='location',
            field=places.fields.PlacesField(max_length=255),
        ),
    ]
