# Generated by Django 3.2.3 on 2021-05-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_auto_20210515_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlet',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='outlet',
            old_name='outlet_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='outlet',
            old_name='retailer',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='outlet',
            old_name='recruiter',
            new_name='registered_by',
        ),
    ]
